version: 2.1
orbs:
  soda-lint: checkmoney/soda-lint@1.0.0
jobs:
  push:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Env
          command: |
            VERSION="${CIRCLE_TAG:-vlatest}"
            echo "export IMAGE_TAG=${VERSION:1}" >> $BASH_ENV
      - run:
          name: Build and push Docker image
          command: |
            source $BASH_ENV
            docker build -t checkmoney/mr-solomons:$IMAGE_TAG .
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker push checkmoney/mr-solomons:$IMAGE_TAG
workflows:
  version: 2
  build:
    jobs:
      - checkmoney/soda-lint:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - push:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
          requires:
            - lint
