version: 2.1
orbs:
  soda-lint: checkmoney/soda-lint@1.0.2
  docker: checkmoney/docker@1.0.3
  jest: checkmoney/jest@1.0.0
  deploy: checkmoney/deploy@1.0.14
workflows:
  version: 2
  build:
    jobs:
      - soda-lint/invoke:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - jest/test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - docker/build_push:
          image_name: "mr-solomons"
          image_version: CIRCLE_TAG
          docker_username: DOCKER_USERNAME
          docker_password: DOCKER_PASSWORD
          filters:
            branches:
              only: master
            tags:
              only: /.*/
          requires:
            - soda-lint/invoke
            - jest/test
      - deploy/roll_out:
          ssh_user: SSH_USER
          ssh_host: SSH_HOST
          image_name: "mr-solomons"
          image_version: CIRCLE_TAG
          path_to_app: PATH_TO_APP
          apply_post_install: true
          container_name: "solomons"
          post_install_script: "yarn evolutions -y"
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - docker/build_push
